[package]
name = "gemini-grs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
hex = "0.4.3"
log = "0.4.22"
nanoid = "0.4.0"
openssl = "0.10.66"
path-clean = "1.0.1"
url = "2.5.2"
